import type { RoomType, Experience, Review, GalleryItem } from './types';
import { IMG } from './images';

export { IMG };

export const ROOMS: RoomType[] = [
  {
    id: 'r1',
    slug: 'superior-room',
    name: 'Superior Room',
    description: 'Perfect for couples seeking a serene retreat. Elegant interiors with warm Rajasthani tones, a plush king-size bed, and a private balcony overlooking the golden city.',
    price: 4500,
    max_guests: 2,
    amenities: ['WiFi', 'AC', 'TV', 'Breakfast', 'Mini Bar', 'Private Bathroom', 'Balcony'],
    image_url: IMG.room1,
    gallery: [IMG.room1, IMG.room2, IMG.room3, IMG.room5],
    is_available: true,
    sort_order: 1,
  },
  {
    id: 'r2',
    slug: 'deluxe-room',
    name: 'Deluxe Room',
    description: 'Premium interior with handcrafted Rajasthani decor, spacious seating area, and a luxurious en-suite bathroom. Designed for guests who appreciate refined comfort.',
    price: 6500,
    max_guests: 2,
    amenities: ['WiFi', 'AC', 'TV', 'Breakfast', 'Mini Bar', 'Private Bathroom', 'Balcony', 'Seating Area'],
    image_url: IMG.room2,
    gallery: [IMG.room2, IMG.room6, IMG.room8, IMG.room1],
    is_available: true,
    sort_order: 2,
  },
  {
    id: 'r3',
    slug: 'family-suite',
    name: 'Family Suite',
    description: 'A large luxury suite perfect for families. Features a separate living area, two bedrooms, and panoramic desert views from a private terrace.',
    price: 9500,
    max_guests: 4,
    amenities: ['WiFi', 'AC', 'TV', 'Breakfast', 'Mini Bar', 'Private Bathroom', 'Living Area', 'Terrace'],
    image_url: IMG.room3,
    gallery: [IMG.room3, IMG.room7, IMG.room4, IMG.room6],
    is_available: true,
    sort_order: 3,
  },
  {
    id: 'r4',
    slug: 'boys-sharing-room',
    name: 'Boys Sharing Room',
    description: 'Affordable shared accommodation with 4 comfortable beds, personal lockers, and air conditioning. Ideal for solo travelers and groups of friends.',
    price: 1200,
    max_guests: 4,
    amenities: ['WiFi', 'AC', 'Locker', 'Shared Bathroom'],
    image_url: IMG.room5,
    gallery: [IMG.room5, IMG.room1],
    is_available: true,
    sort_order: 4,
  },
  {
    id: 'r5',
    slug: 'girls-sharing-room',
    name: 'Girls Sharing Room',
    description: 'Female-only shared accommodation in a safe, secure, and private area. Features comfortable beds, personal lockers, and air conditioning.',
    price: 1200,
    max_guests: 4,
    amenities: ['WiFi', 'AC', 'Locker', 'Shared Bathroom', 'Private Area'],
    image_url: IMG.room6,
    gallery: [IMG.room6, IMG.room2],
    is_available: true,
    sort_order: 5,
  },
];

export const EXPERIENCES: Experience[] = [
  {
    id: 'e1',
    slug: 'camel-safari',
    title: 'Camel Safari',
    category: 'Safari',
    short_description: 'Ride through the golden dunes of the Thar Desert on a traditional camel caravan.',
    description: 'Embark on a timeless journey across the rolling sand dunes of the Thar Desert. Our camel safari takes you deep into the heart of Rajasthan\'s golden landscape, where you\'ll experience the silence of the desert, the warmth of the setting sun, and the hospitality of desert guides. Choose from morning, evening, or sunset safaris — each offering a unique perspective on this ancient landscape.',
    highlights: ['Traditional camel ride', 'Golden sand dunes', 'Professional desert guide', 'Photo opportunities', 'Sunset views', 'Cultural immersion'],
    duration: '2–4 hours',
    best_time: 'October to March',
    location: 'Sam Sand Dunes, Jaisalmer',
    included: ['Camel ride', 'Desert guide', 'Bottled water', 'Pickup & drop from hotel'],
    excluded: ['Personal expenses', 'Tips', 'Travel insurance'],
    itinerary: [
      { time: '3:00 PM', activity: 'Pickup from hotel in a private jeep' },
      { time: '3:45 PM', activity: 'Arrive at Sam Sand Dunes, meet your camel guide' },
      { time: '4:00 PM', activity: 'Begin camel safari across the dunes' },
      { time: '5:30 PM', activity: 'Reach sunset point, refreshments served' },
      { time: '6:00 PM', activity: 'Watch the spectacular desert sunset' },
      { time: '6:30 PM', activity: 'Return camel ride to base camp' },
      { time: '7:30 PM', activity: 'Drop back to hotel' },
    ],
    price: 1500,
    image_url: IMG.camel1,
    gallery: [IMG.camel1, IMG.camel2, IMG.camel3, IMG.camel4, IMG.camel5, IMG.camel6],
    is_featured: true,
    sort_order: 1,
  },
  {
    id: 'e2',
    slug: 'jeep-safari',
    title: 'Jeep Safari',
    category: 'Adventure',
    short_description: 'Thrilling 4x4 off-road adventure across the dunes and desert terrain.',
    description: 'Experience the adrenaline rush of a 4x4 jeep safari across the rugged desert terrain. Our powerful jeeps take you to places camels cannot reach — through dry riverbeds, over steep dunes, and to hidden desert viewpoints. Perfect for adventure seekers who want to cover more ground and feel the thrill of off-road driving in the Thar Desert.',
    highlights: ['4x4 off-road adventure', 'Professional driver', 'Dune bashing', 'Sunset ride', 'Desert viewpoints', 'Group or private options'],
    duration: '2–3 hours',
    best_time: 'October to March',
    location: 'Sam Sand Dunes, Jaisalmer',
    included: ['Jeep with driver', 'Fuel', 'Desert guide', 'Bottled water', 'Pickup & drop'],
    excluded: ['Personal expenses', 'Tips', 'Travel insurance'],
    itinerary: [
      { time: '3:30 PM', activity: 'Pickup from hotel' },
      { time: '4:00 PM', activity: 'Arrive at desert, safety briefing' },
      { time: '4:15 PM', activity: 'Off-road dune bashing begins' },
      { time: '5:30 PM', activity: 'Reach panoramic sunset viewpoint' },
      { time: '6:00 PM', activity: 'Sunset photography session' },
      { time: '6:45 PM', activity: 'Return drive and drop at hotel' },
    ],
    price: 2500,
    image_url: IMG.jeep1,
    gallery: [IMG.jeep1, IMG.jeep2, IMG.jeep3, IMG.jeep4],
    is_featured: true,
    sort_order: 2,
  },
  {
    id: 'e3',
    slug: 'sam-sand-dunes-camp',
    title: 'Sam Sand Dunes Camp',
    category: 'Desert Camp',
    short_description: 'Luxury Swiss tent camping at Sam Sand Dunes with cultural evening and stargazing.',
    description: 'Spend an unforgettable night under the stars at our luxury desert camp at Sam Sand Dunes. Stay in a premium Swiss tent with comfortable bedding and modern amenities. Enjoy camel rides at sunset, live folk music and dance, a bonfire, and a traditional Rajasthani dinner. Wake up to morning tea served at your tent and breakfast with desert views.',
    highlights: ['Luxury Swiss tent', 'Camel ride at sunset', 'Live folk music & dance', 'Bonfire night', 'Traditional Rajasthani dinner', 'Sleeping under the stars', 'Morning tea & breakfast'],
    duration: 'Overnight (1 night)',
    best_time: 'October to March',
    location: 'Sam Sand Dunes, Jaisalmer',
    included: ['Swiss tent accommodation', 'Camel ride', 'Evening cultural program', 'Bonfire', 'Dinner', 'Morning tea & breakfast', 'Pickup & drop'],
    excluded: ['Personal expenses', 'Tips', 'Alcoholic beverages', 'Travel insurance'],
    itinerary: [
      { time: '3:00 PM', activity: 'Pickup from hotel, drive to Sam Dunes' },
      { time: '4:00 PM', activity: 'Welcome drink, check into Swiss tent' },
      { time: '4:30 PM', activity: 'Camel ride to sunset point' },
      { time: '6:00 PM', activity: 'Sunset at the dunes' },
      { time: '7:00 PM', activity: 'Return to camp, bonfire & cultural evening' },
      { time: '8:00 PM', activity: 'Traditional Rajasthani dinner buffet' },
      { time: '9:30 PM', activity: 'Stargazing and sleeping under the stars' },
      { time: '6:00 AM', activity: 'Morning tea served at tent' },
      { time: '7:30 AM', activity: 'Breakfast with desert views' },
      { time: '9:00 AM', activity: 'Check out and return to Jaisalmer' },
    ],
    price: 5500,
    image_url: IMG.camp1,
    gallery: [IMG.camp1, IMG.camp2, IMG.camp3, IMG.camp4, IMG.camp5, IMG.camp6],
    is_featured: true,
    sort_order: 3,
  },
  {
    id: 'e4',
    slug: 'sleeping-under-the-stars',
    title: 'Sleeping Under the Stars',
    category: 'Desert Camp',
    short_description: 'A magical night sleeping in the open desert under a canopy of stars.',
    description: 'The ultimate desert experience — sleep in the open air on a luxury bed surrounded by the silence of the Thar Desert. Enjoy a private bonfire, live music, sky photography, and a gourmet dinner. Wake up to the first light of dawn and breakfast served in the wild. This is the most intimate and exclusive way to experience the desert.',
    highlights: ['Open-air luxury bedding', 'Private bonfire', 'Live music', 'Sky photography session', 'Gourmet dinner', 'Breakfast in the wild'],
    duration: 'Overnight (1 night)',
    best_time: 'October to March',
    location: 'Sam Sand Dunes, Jaisalmer',
    included: ['Luxury bedding setup', 'Private bonfire', 'Live music', 'Dinner', 'Breakfast', 'Pickup & drop'],
    excluded: ['Personal expenses', 'Tips', 'Alcoholic beverages', 'Travel insurance'],
    itinerary: [
      { time: '4:00 PM', activity: 'Pickup from hotel' },
      { time: '5:00 PM', activity: 'Arrive at desert, setup and welcome' },
      { time: '6:00 PM', activity: 'Sunset viewing and photography' },
      { time: '7:30 PM', activity: 'Bonfire and live music' },
      { time: '8:30 PM', activity: 'Gourmet dinner under the stars' },
      { time: '10:00 PM', activity: 'Sky photography session' },
      { time: '6:00 AM', activity: 'Sunrise and morning tea' },
      { time: '7:30 AM', activity: 'Breakfast in the wild' },
      { time: '9:00 AM', activity: 'Return to hotel' },
    ],
    price: 7500,
    image_url: IMG.camp3,
    gallery: [IMG.camp3, IMG.camp5, IMG.camp6, IMG.camp2, IMG.camp4],
    is_featured: true,
    sort_order: 4,
  },
  {
    id: 'e5',
    slug: 'india-pakistan-border-tour',
    title: 'India–Pakistan Border Tour',
    category: 'Tour',
    short_description: 'Visit Tanot Mata Temple, Longewala War Memorial, and the historic border battlefield.',
    description: 'A deeply moving and patriotic journey to the India–Pakistan border. Visit the sacred Tanot Mata Temple, the Longewala War Memorial commemorating the 1971 battle, and the army museum. Learn the history of bravery and sacrifice, capture stunning photographs of the desert landscape, and experience the pride of standing at India\'s western frontier.',
    highlights: ['Tanot Mata Temple', 'Longewala War Memorial', 'Army museum', 'Battlefield history', 'Desert landscape photography', 'Lunch included'],
    duration: 'Full day (8–10 hours)',
    best_time: 'October to March',
    location: 'Tanot & Longewala, Rajasthan',
    included: ['Private cab', 'Fuel', 'Driver cum guide', 'Lunch', 'Entry fees', 'Pickup & drop'],
    excluded: ['Personal expenses', 'Tips', 'Travel insurance'],
    itinerary: [
      { time: '7:00 AM', activity: 'Pickup from hotel' },
      { time: '9:30 AM', activity: 'Arrive at Tanot Mata Temple, darshan' },
      { time: '10:30 AM', activity: 'Drive to Longewala War Memorial' },
      { time: '11:30 AM', activity: 'Visit memorial and army museum' },
      { time: '1:00 PM', activity: 'Lunch at local restaurant' },
      { time: '2:00 PM', activity: 'Photography at battlefield site' },
      { time: '3:30 PM', activity: 'Begin return journey' },
      { time: '6:00 PM', activity: 'Drop at hotel' },
    ],
    price: 3500,
    image_url: IMG.fort2,
    gallery: [IMG.fort2, IMG.dunes1, IMG.dunes2, IMG.fort8],
    is_featured: true,
    sort_order: 5,
  },
  {
    id: 'e6',
    slug: 'jaisalmer-city-tour',
    title: 'Jaisalmer City Tour',
    category: 'Tour',
    short_description: 'Explore Patwon Ki Haveli, Nathmal Ki Haveli, Jaisalmer Fort, Gadisar Lake, and more.',
    description: 'Discover the golden city\'s most iconic landmarks with an expert local guide. Visit the intricately carved Patwon Ki Haveli, Nathmal Ki Haveli, and Salim Singh Ki Haveli. Explore the magnificent Jaisalmer Fort, a living fort with temples and palaces. Stroll around Gadisar Lake, visit Bada Bagh, and enjoy shopping in the vibrant local markets.',
    highlights: ['Patwon Ki Haveli', 'Nathmal Ki Haveli', 'Salim Singh Ki Haveli', 'Jaisalmer Fort', 'Gadisar Lake', 'Bada Bagh', 'Local market shopping'],
    duration: 'Half day (5–6 hours)',
    best_time: 'October to March',
    location: 'Jaisalmer City',
    included: ['Private cab', 'Expert guide', 'Entry fees', 'Bottled water', 'Pickup & drop'],
    excluded: ['Personal expenses', 'Tips', 'Lunch', 'Travel insurance'],
    itinerary: [
      { time: '9:00 AM', activity: 'Pickup from hotel' },
      { time: '9:30 AM', activity: 'Visit Jaisalmer Fort & Jain temples' },
      { time: '11:00 AM', activity: 'Patwon Ki Haveli' },
      { time: '12:00 PM', activity: 'Nathmal Ki Haveli & Salim Singh Ki Haveli' },
      { time: '1:00 PM', activity: 'Lunch break (own expense)' },
      { time: '2:00 PM', activity: 'Gadisar Lake & Bada Bagh' },
      { time: '3:30 PM', activity: 'Local market shopping' },
      { time: '4:30 PM', activity: 'Drop at hotel' },
    ],
    price: 2000,
    image_url: IMG.fort1,
    gallery: [IMG.fort1, IMG.fort3, IMG.fort4, IMG.fort5, IMG.fort6, IMG.fort7],
    is_featured: true,
    sort_order: 6,
  },
  {
    id: 'e7',
    slug: 'desert-camp',
    title: 'Desert Camp',
    category: 'Desert Camp',
    short_description: 'Overnight desert camping with cultural evening, bonfire, and stargazing.',
    description: 'Experience the magic of the Thar Desert with an overnight camping adventure. Enjoy a beautiful sunset, camel rides, live folk music and dance, a warm bonfire, and a delicious traditional dinner. Sleep in comfort and wake up to the peaceful silence of the desert morning.',
    highlights: ['Overnight camping', 'Camel ride', 'Folk music & dance', 'Bonfire', 'Traditional dinner', 'Stargazing'],
    duration: 'Overnight (1 night)',
    best_time: 'October to March',
    location: 'Sam Sand Dunes, Jaisalmer',
    included: ['Tent accommodation', 'Camel ride', 'Cultural evening', 'Bonfire', 'Dinner', 'Breakfast', 'Pickup & drop'],
    excluded: ['Personal expenses', 'Tips', 'Alcoholic beverages', 'Travel insurance'],
    itinerary: [
      { time: '3:30 PM', activity: 'Pickup from hotel' },
      { time: '4:30 PM', activity: 'Arrive at camp, welcome drink' },
      { time: '5:00 PM', activity: 'Camel ride to sunset point' },
      { time: '7:00 PM', activity: 'Cultural evening with folk music & dance' },
      { time: '8:00 PM', activity: 'Bonfire and dinner' },
      { time: '6:30 AM', activity: 'Morning tea and breakfast' },
      { time: '9:00 AM', activity: 'Return to hotel' },
    ],
    price: 3500,
    image_url: IMG.camp4,
    gallery: [IMG.camp4, IMG.camp1, IMG.camp5, IMG.camp6],
    is_featured: false,
    sort_order: 7,
  },
  {
    id: 'e8',
    slug: 'sunset-safari',
    title: 'Sunset Safari',
    category: 'Safari',
    short_description: 'A magical evening safari to witness the desert sunset in all its glory.',
    description: 'Watch the sun dip below the golden dunes in a blaze of orange and gold. Our sunset safari combines a camel or jeep ride with a dedicated sunset viewing point, complete with refreshments and photography opportunities. The perfect way to end a day in Jaisalmer.',
    highlights: ['Sunset at the dunes', 'Camel or jeep ride', 'Photography opportunities', 'Refreshments', 'Desert guide'],
    duration: '2 hours',
    best_time: 'October to March',
    location: 'Sam Sand Dunes, Jaisalmer',
    included: ['Camel or jeep ride', 'Desert guide', 'Refreshments', 'Pickup & drop'],
    excluded: ['Personal expenses', 'Tips', 'Travel insurance'],
    itinerary: [
      { time: '4:00 PM', activity: 'Pickup from hotel' },
      { time: '4:45 PM', activity: 'Arrive at dunes, begin safari' },
      { time: '5:45 PM', activity: 'Reach sunset viewpoint' },
      { time: '6:00 PM', activity: 'Sunset viewing & photography' },
      { time: '6:45 PM', activity: 'Return and drop at hotel' },
    ],
    price: 1800,
    image_url: IMG.camel5,
    gallery: [IMG.camel5, IMG.camel6, IMG.dunes3, IMG.dunes1],
    is_featured: false,
    sort_order: 8,
  },
  {
    id: 'e9',
    slug: 'cultural-evening',
    title: 'Cultural Evening',
    category: 'Culture',
    short_description: 'Live Rajasthani folk music and dance performance under the open sky.',
    description: 'Immerse yourself in the vibrant culture of Rajasthan with an evening of live folk music and dance. Watch traditional Kalbeliya, Ghoomar, and Bhavai performances by professional artists. Enjoy the rhythms of the dholak and the melodies of the ravanhatta in an intimate desert setting.',
    highlights: ['Live folk music', 'Traditional dance performances', 'Professional artists', 'Open sky venue', 'Cultural immersion'],
    duration: '2 hours',
    best_time: 'October to March',
    location: 'The Dara Jaisalmer',
    included: ['Live performance', 'Seating', 'Welcome drink'],
    excluded: ['Personal expenses', 'Dinner (optional add-on)'],
    itinerary: [
      { time: '7:00 PM', activity: 'Welcome and seating' },
      { time: '7:15 PM', activity: 'Folk music performance begins' },
      { time: '7:45 PM', activity: 'Traditional dance performances' },
      { time: '8:30 PM', activity: 'Audience interaction and photos' },
      { time: '9:00 PM', activity: 'End of performance' },
    ],
    price: 800,
    image_url: IMG.cultural1,
    gallery: [IMG.cultural1, IMG.cultural2, IMG.cultural3, IMG.cultural4, IMG.cultural5],
    is_featured: false,
    sort_order: 9,
  },
  {
    id: 'e10',
    slug: 'heritage-walk',
    title: 'Heritage Walk',
    category: 'Tour',
    short_description: 'A guided walk through Jaisalmer\'s narrow lanes and hidden architectural gems.',
    description: 'Wander through the golden lanes of Jaisalmer with a knowledgeable local guide. Discover hidden havelis, ancient temples, and secret viewpoints that most tourists miss. Learn the stories and legends behind the golden city\'s 900-year history.',
    highlights: ['Guided heritage walk', 'Hidden havelis', 'Ancient temples', 'Local stories & legends', 'Secret viewpoints'],
    duration: '3 hours',
    best_time: 'October to March',
    location: 'Jaisalmer Old City',
    included: ['Expert guide', 'Walking tour', 'Bottled water'],
    excluded: ['Personal expenses', 'Entry fees', 'Tips'],
    itinerary: [
      { time: '8:00 AM', activity: 'Meet at hotel, begin walk' },
      { time: '8:30 AM', activity: 'Explore old city lanes' },
      { time: '9:30 AM', activity: 'Visit hidden havelis & temples' },
      { time: '10:30 AM', activity: 'Secret viewpoint & stories' },
      { time: '11:00 AM', activity: 'End of walk' },
    ],
    price: 1000,
    image_url: IMG.fort4,
    gallery: [IMG.fort4, IMG.fort5, IMG.fort7, IMG.fort8],
    is_featured: false,
    sort_order: 10,
  },
];

export const REVIEWS: Review[] = [
  { id: 'rv1', guest_name: 'Aarav & Diya Sharma', rating: 5, title: 'Unforgettable desert experience', body: 'The camel safari at sunset was magical. The staff went above and beyond to make our anniversary special. The Swiss tent was luxurious and the cultural evening was the highlight of our trip.', experience_id: 'e3', room_type_id: 'r2', is_approved: true, created_at: '2024-12-15' },
  { id: 'rv2', guest_name: 'James Whitmore', rating: 5, title: 'Best hotel in Jaisalmer', body: 'As a solo traveler from the UK, I felt incredibly well taken care of. The boys sharing room was clean and comfortable, and the border tour was a deeply moving experience. Highly recommended.', experience_id: 'e5', room_type_id: 'r4', is_approved: true, created_at: '2024-11-20' },
  { id: 'rv3', guest_name: 'Priya Nair', rating: 5, title: 'Perfect family getaway', body: 'The family suite was spacious and beautifully decorated. The kids loved the camel ride and bonfire. The food was authentic and delicious. Will definitely return!', experience_id: null, room_type_id: 'r3', is_approved: true, created_at: '2025-01-05' },
  { id: 'rv4', guest_name: 'Sophie Laurent', rating: 5, title: 'Sleeping under the stars', body: 'This was the most romantic experience of my life. Sleeping in the open desert under a blanket of stars, with a private bonfire and live music — pure magic. The Dara team is exceptional.', experience_id: 'e4', room_type_id: null, is_approved: true, created_at: '2025-01-10' },
  { id: 'rv5', guest_name: 'Rohan Mehta', rating: 5, title: 'Outstanding service', body: 'From booking to checkout, everything was seamless. The jeep safari was thrilling and the city tour was informative. The heritage hotel itself is a work of art.', experience_id: 'e2', room_type_id: 'r1', is_approved: true, created_at: '2024-10-28' },
  { id: 'rv6', guest_name: 'Emma Chen', rating: 5, title: 'A piece of paradise', body: 'The girls sharing room felt safe and private. The rooftop dinner with traditional Rajasthani food was incredible. The staff are warm and genuinely caring.', experience_id: null, room_type_id: 'r5', is_approved: true, created_at: '2024-12-01' },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  { id: 'g1', category: 'Desert', title: 'Golden Dunes', image_url: IMG.dunes2, sort_order: 1 },
  { id: 'g2', category: 'Safari', title: 'Camel Caravan', image_url: IMG.camel2, sort_order: 2 },
  { id: 'g3', category: 'Rooms', title: 'Deluxe Room', image_url: IMG.room2, sort_order: 3 },
  { id: 'g4', category: 'Desert', title: 'Desert Sunset', image_url: IMG.dunes3, sort_order: 4 },
  { id: 'g5', category: 'Safari', title: 'Jeep Adventure', image_url: IMG.jeep1, sort_order: 5 },
  { id: 'g6', category: 'Food', title: 'Rajasthani Thali', image_url: IMG.food1, sort_order: 6 },
  { id: 'g7', category: 'Events', title: 'Cultural Evening', image_url: IMG.cultural1, sort_order: 7 },
  { id: 'g8', category: 'Desert', title: 'Night Camp', image_url: IMG.camp3, sort_order: 8 },
  { id: 'g9', category: 'Rooms', title: 'Family Suite', image_url: IMG.room3, sort_order: 9 },
  { id: 'g10', category: 'Border Tour', title: 'Longewala Memorial', image_url: IMG.fort2, sort_order: 10 },
  { id: 'g11', category: 'Wedding', title: 'Palace Wedding', image_url: IMG.wedding1, sort_order: 11 },
  { id: 'g12', category: 'Safari', title: 'Sunset Ride', image_url: IMG.camel5, sort_order: 12 },
  { id: 'g13', category: 'Food', title: 'Fine Dining', image_url: IMG.restaurant2, sort_order: 13 },
  { id: 'g14', category: 'Events', title: 'Folk Dance', image_url: IMG.cultural3, sort_order: 14 },
  { id: 'g15', category: 'Desert', title: 'Starry Night', image_url: IMG.camp5, sort_order: 15 },
  { id: 'g16', category: 'Border Tour', title: 'Tanot Temple', image_url: IMG.dunes1, sort_order: 16 },
  { id: 'g17', category: 'Wedding', title: 'Decor & Venue', image_url: IMG.wedding3, sort_order: 17 },
  { id: 'g18', category: 'Rooms', title: 'Superior Room', image_url: IMG.room1, sort_order: 18 },
];

export const GALLERY_CATEGORIES = ['All', 'Rooms', 'Desert', 'Safari', 'Food', 'Events', 'Wedding', 'Border Tour'];

export const STATS = [
  { label: 'Guests Served', value: 12000, suffix: '+' },
  { label: 'Years of Hospitality', value: 15, suffix: '+' },
  { label: 'Luxury Rooms', value: 48, suffix: '' },
  { label: 'Happy Guests', value: 9500, suffix: '+' },
  { label: 'Safari Tours', value: 8000, suffix: '+' },
  { label: '5 Star Reviews', value: 2100, suffix: '+' },
];

export const PICKUP_LOCATIONS = ['Airport', 'Railway Station', 'Bus Stand', 'Other'];

export const CONTACT = {
  phone: '+91 90000 00000',
  whatsapp: '919000000000',
  email: 'stay@thedarajaisalmer.com',
  address: 'Sam Road, Near Sam Sand Dunes, Jaisalmer, Rajasthan 345001, India',
  hours: 'Open 24 hours, 7 days a week',
  emergency: '+91 90000 00001',
  instagram: 'https://instagram.com/thedarajaisalmer',
  mapEmbed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3564.5!2d70.9!3d26.9!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMjbCsDU0JzAuMCJOIDcwwrA1NCcwLjAiRQ!5e0!3m2!1sen!2sin!4v1700000000000',
};
